### ISSUE TITLE
Deadlock in json_prolog

### ISSUE THREAD

**Issue by marcniehaus** [knowrob/knowrob#107]
Hello KnowRob-Team,

I am using KnowRob in combination with the CRAM2 bullet reasoining environment for an evaluation. I have a scenario similar to the spatial_relations_demo. The only difference is that I try to achieve the "object-in-hand" goal for an object which does not exist in the simulation. During the tries to grasp the object KnowRob (probably json_prolog) encounters a deadlock. If I close and reopen LISP the kitchen environment is not spawned anymore. This can only fixed by restarting the json prolog node.
When I attached a debugger to json_prolog I saw some threads hanging at ThreadQuery:130 and one at ThreadQuery:81.
To get my evaluation done, I first tried an old KnowRob-Version (9551075871ef02b423127a90eed3179487cc4f2e) and the deadlock still occured. Afterwards, I tried an older version (35faec323c626dcd7d3b9765561ba290b6526f73) and the deadlock did not appear anymore. I tried to revert the commits between 35faec323c626dcd7d3b9765561ba290b6526f73 and HEAD making changes to ThreadedQuery.java and JSONPrologNode.java but the deadlock was still there...

Kind Regards,

Marc Niehaus

Edit: The deadlock still occurs is still there in 35faec323c626dcd7d3b9765561ba290b6526f73. However, it occurs less frequent...

**Comment by daniel86** [comment]
i guess I fixed it recently
