### ISSUE TITLE
Is Knowrob team going to update http://wiki.ros.org/rosprolog to kinetic  ?

### ISSUE THREAD

**Issue by logicmoo** [knowrob/knowrob#108]
Is Knowrob team going to update http://wiki.ros.org/rosprolog to kinetic  ?

**Comment by daniel86** [comment]
Hi @logicmoo, yes I will work on that later this year.
Are there any issues you ran into?

**Comment by daniel86** [comment]
Duplicate of https://github.com/knowrob/knowrob/issues/118
