### ISSUE TITLE
Update install tutorial, add required dependencies

### ISSUE THREAD

**Issue by andreihaidu** [knowrob/knowrob#111]
List of dependencies which I needed:

from [code_iai](https://github.com/code-iai):
- iai_cad_tools
- iai_common_msgs

mjpeg_server:
http://wiki.ros.org/mjpeg_server

rosbridge_server:
apt-get install ros-indigo-rosbridge-server

json:
apt-get install libjson-glib-dev

**Comment by fairlight1337** [comment]
I can confirm that

**Comment by andreihaidu** [comment]
Update:
apt-get install swi-prolog-java

**Comment by daniel86** [comment]
@andreihaidu to which install tutorial are you referring?

**Comment by andreihaidu** [comment]
Not a tutorial per se, if one clones the repository and wants to build it via catkin.

**Comment by JKBehrens** [comment]
I used @gheorghelisca s workspace setup (https://github.com/gheorghelisca/ros_indigo_workspaces) to install Knowrob, CRAM, semrec and so on. I documented the whole process (last week). For knowrob, I needed to do:
`sudo apt-get install ros-indigo-rosjava* ros-indigo-mjpeg-server ros-indigo-rosbridge-server swi-prolog libjson-glib-dev`

**Comment by prfiredragon** [comment]
Thank you for sharing the  workspace setup link. I was searching for something like that. That help me alot.
