### ISSUE TITLE
java.security.InvalidKeyException: EC parameters error

### ISSUE THREAD

**Issue by joselpart** [knowrob/knowrob#145]
Hi, today I installed Knowrob following the instructions in the website and at the end of the build, I was getting this error, which in turn was preventing knowrob_vis to work since some of the classes (particularly DiagramVisualization) were not compiled:

Exception in thread "main" javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error

The way I fixed it was by compiling against Java 8.

**Comment by asilx** [comment]
We already knew about this issue. Thanks for reporting

**Comment by daniel86** [comment]
closing the ticket because we can't do anything about it
