### ISSUE TITLE
knowrob_objects/DirtyObject.h: No such file or director

### ISSUE THREAD

**Issue by sasjonge** [knowrob/knowrob#177]
Hello,

if I try to build master I get the following error:

`.../knowrob/knowrob_objects/src/knowrob_objects.cpp:6:41: fatal error: knowrob_objects/DirtyObject.h: No such file or directory
compilation terminated.
knowrob/knowrob_objects/CMakeFiles/knowrob_objects.dir/build.make:62: recipe for target 'knowrob/knowrob_objects/CMakeFiles/knowrob_objects.dir/src/knowrob_objects.cpp.o' failed
`

I can reproduce the same error on my local installation and if I try to build the openease/kinetic-knowrob-daemon if I change the used branch of knowrob to mother in the dockerbuild file.

**Comment by daniel86** [comment]
should be fixed in master branch with https://github.com/knowrob/knowrob/commit/d026512f94547fa852d9127f69feabfd24168720
