### ISSUE TITLE
missing(wrong) rule in comp_similarity.pl

### ISSUE THREAD

**Issue by bbferka** [knowrob/knowrob#183]
I was looking for some way of returning similar entries from the ontology (e.g. other classes of some super type that an object might have) and came across the following rule in knowrob_common/prolog/comp_similarity.pl: 
``rdf_most_similar(Class, Super, N, NMostSim) ``

Unfortunatelly this uses a rule: ``rdf_wup_distance`` that has no implementation; 
It works by replacing ``rdf_wup_distance`` with ``rdf_wup_similarity``

To reconstruct:
``
rosrun rosprolog rosprolog knowrob_common
rdf_most_similar(knowrob:'Thermos',knowrob:'Container',5,N).``

``ERROR: '<meta-call>'/1: Undefined procedure: comp_similarity:rdf_wup_distance/3``

I am running 16.04 kinetic branch of Knowrob

**Comment by daniel86** [comment]
thanks for the report, will fix it now
