### ISSUE TITLE
some error when I catkin_make.

### ISSUE THREAD

**Issue by JonyUnbroken** [knowrob/knowrob#202]
[100%] Built target gradle-knowrob_common
[100%] Gradling tasks for knowrob_srdl
[100%] Gradling tasks for knowrob_mongo
[100%] Gradling tasks for json_prolog

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':knowrob_mongo:compile'.
> Could not find any version that matches org.knowrob.tfjava:tfjava:[0.1,).
  Required by:
      org.knowrob.knowrob_mongo:knowrob_mongo:0.1.0
> Could not find any version that matches org.knowrob.knowrob_common:knowrob_common:[0.1,).
  Required by:
      org.knowrob.knowrob_mongo:knowrob_mongo:0.1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
knowrob/knowrob_mongo/CMakeFiles/gradle-knowrob_mongo.dir/build.make:57: recipe for target 'knowrob/knowrob_mongo/CMakeFiles/gradle-knowrob_mongo' failed
make[2]: *** [knowrob/knowrob_mongo/CMakeFiles/gradle-knowrob_mongo] Error 1
CMakeFiles/Makefile2:12009: recipe for target 'knowrob/knowrob_mongo/CMakeFiles/gradle-knowrob_mongo.dir/all' failed
make[1]: *** [knowrob/knowrob_mongo/CMakeFiles/gradle-knowrob_mongo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':json_prolog:compile'.
> Could not find any version that matches org.knowrob.knowrob_common:knowrob_common:[0.1,).
  Searched in the following locations:
      file:/home/jony/knowrob_ws/devel/share/maven/org/knowrob/knowrob_common/knowrob_common/maven-metadata.xml
      file:/home/jony/knowrob_ws/devel/share/maven/org/knowrob/knowrob_common/knowrob_common/
      file:/home/jony/moveit_ws/devel/share/maven/org/knowrob/knowrob_common/knowrob_common/maven-metadata.xml
      file:/home/jony/moveit_ws/devel/share/maven/org/knowrob/knowrob_common/knowrob_common/
      file:/home/jony/ws_moveit/devel/share/maven/org/knowrob/knowrob_common/knowrob_common/maven-metadata.xml
      file:/home/jony/ws_moveit/devel/share/maven/org/knowrob/knowrob_common/knowrob_common/
      file:/opt/ros/kinetic/share/maven/org/knowrob/knowrob_common/knowrob_common/maven-metadata.xml
      file:/opt/ros/kinetic/share/maven/org/knowrob/knowrob_common/knowrob_common/
      https://github.com/rosjava/rosjava_mvn_repo/raw/master/org/knowrob/knowrob_common/knowrob_common/maven-metadata.xml
      https://github.com/rosjava/rosjava_mvn_repo/raw/master/org/knowrob/knowrob_common/knowrob_common/
      file:/home/jony/.m2/repository/org/knowrob/knowrob_common/knowrob_common/maven-metadata.xml
      file:/home/jony/.m2/repository/org/knowrob/knowrob_common/knowrob_common/
      http://repository.springsource.com/maven/bundles/release/org/knowrob/knowrob_common/knowrob_common/maven-metadata.xml
      http://repository.springsource.com/maven/bundles/release/org/knowrob/knowrob_common/knowrob_common/
      http://repository.springsource.com/maven/bundles/external/org/knowrob/knowrob_common/knowrob_common/maven-metadata.xml
      http://repository.springsource.com/maven/bundles/external/org/knowrob/knowrob_common/knowrob_common/
      https://repo1.maven.org/maven2/org/knowrob/knowrob_common/knowrob_common/maven-metadata.xml
      https://repo1.maven.org/maven2/org/knowrob/knowrob_common/knowrob_common/
  Required by:
      org.knowrob.json_prolog:json_prolog:0.1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
knowrob/json_prolog/CMakeFiles/gradle-json_prolog.dir/build.make:57: recipe for target 'knowrob/json_prolog/CMakeFiles/gradle-json_prolog' failed
make[2]: *** [knowrob/json_prolog/CMakeFiles/gradle-json_prolog] Error 1
CMakeFiles/Makefile2:11151: recipe for target 'knowrob/json_prolog/CMakeFiles/gradle-json_prolog.dir/all' failed
make[1]: *** [knowrob/json_prolog/CMakeFiles/gradle-json_prolog.dir/all] Error 2

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':knowrob_srdl:compile'.
> Could not find any version that matches org.knowrob.knowrob_common:knowrob_common:[0.1,).
  Required by:
      org.knowrob.knowrob_srdl:knowrob_srdl:0.1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
knowrob/knowrob_srdl/CMakeFiles/gradle-knowrob_srdl.dir/build.make:57: recipe for target 'knowrob/knowrob_srdl/CMakeFiles/gradle-knowrob_srdl' failed
make[2]: *** [knowrob/knowrob_srdl/CMakeFiles/gradle-knowrob_srdl] Error 1
CMakeFiles/Makefile2:12101: recipe for target 'knowrob/knowrob_srdl/CMakeFiles/gradle-knowrob_srdl.dir/all' failed
make[1]: *** [knowrob/knowrob_srdl/CMakeFiles/gradle-knowrob_srdl.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by daniel86** [comment]
Hi @JonyUnbroken 

It seems to be some issue with your ROS workspace or ROS installation.
The packages that can not be found by gradle are in fact part of KnowRob.
Can't tell what is going wrong from what you pasted, sorry.

I am closing the issue, because it is nothing I could fix in KnowRob.

What is your the ROS version, and what branch are you using?
If you run ROS kinetic make sure to use the kinetic branch.
lunar and melodic are not yet supported/tested.
