### ISSUE TITLE
install knowrob in kinetic problems

### ISSUE THREAD

**Issue by ablazexu** [knowrob/knowrob#213]
Hello,
I've tried to install the knowrob kinetic branch under Ubuntu 16.04.
However, when I run the catkin-make, I got this build error:

[  4%] Built target roscpp_generate_messages_py
/usr/bin/ld: cannot find -lswipl
collect2: error: ld returned 1 exit status
knowrob/rosprolog/CMakeFiles/rosprolog.dir/build.make:123: recipe for target '/home/robot/catkin_knowrob/devel/lib/librosprolog.so' failed
make[2]: *** [/home/robot/catkin_knowrob/devel/lib/librosprolog.so] Error 1
CMakeFiles/Makefile2:667: recipe for target 'knowrob/rosprolog/CMakeFiles/rosprolog.dir/all' failed
make[1]: *** [knowrob/rosprolog/CMakeFiles/rosprolog.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Please give some helps for this problem. Thank you in advance.

**Comment by daniel86** [comment]
You need to *apt-get install swi-prolog*
