### ISSUE TITLE
Python package 'future' required to run rosprolog_commandline.py in ROS melodic (python 2.7)

### ISSUE THREAD

**Issue by chcorbato** [knowrob/knowrob#274]
### Description
When trying to use `rosprolog_commandline.py`, I get the following error:
```
$ rosrun rosprolog rosprolog_commandline.py
Traceback (most recent call last):
  File "/home/parallels/harsh_knowrob_ws/src/rosprolog/scripts/rosprolog_commandline.py", line 6, in <module>
    from builtins import input
ImportError: No module named builtins
```

### Your environment
- ROS distro: melodic
- OS version: Ubuntu 18.04
- Python 2.7

### Steps to reproduce
1. Install knowrob according to README
2. start knowrob with `roslaunch knowrob knowrob.launch`
3. In a new terminal, run `rosrun rosprolog rosprolog_commandline.py`

### Suggested approach
Include python package `future` in the installation requirements

**Comment by daniel86** [comment]
Hello Carlos,

thanks for the report!
I added "python-future" to package.xml#run_depend of rosprolog.
That should fix the problem, I think.

Best,
Daniel
