### ISSUE TITLE
Fix documentation generation

### ISSUE THREAD

**Issue by knowrob** [knowrob/knowrob#30]
The generation of the API docs is currently broken because it has not yet been ported from the ias.cs.tum.edu domain. Either
a) manually install API docs on knowrob.org, or
b) set up automated doc generation and deployment (preferred)

**Comment by JKBehrens** [comment]
Is this still unresolved? At least I can't read the API documentation. I would highly appreciate, if I can get access to the json_prolog API documentation.
Thank you!

**Comment by daniel86** [comment]
I have not looked into doc generation yet, sorry.
Will do that later this year.

**Comment by daniel86** [comment]
works again
