### ISSUE TITLE
Lost difference between `double` and `float` in MongoDB

### ISSUE THREAD

**Issue by JeremiasThun** [knowrob/knowrob#314]
When recording data with KnowRob, it gets stored in MongoDB. But as stated at https://docs.mongodb.com/manual/reference/bson-types/ MongoDB has no distinction between `double` and `float` data types. Both are handled the same way: as `Decimal128`.

KnowRob's ontologies however do contain different restrictions on those data types for different OWL classes. For example:

https://github.com/knowrob/knowrob/blob/4d7af5484683cf2ff0aedd3b0126ae8c5077e035/owl/knowrob.owl#L1028-L1031

and

https://github.com/knowrob/knowrob/blob/4d7af5484683cf2ff0aedd3b0126ae8c5077e035/owl/knowrob.owl#L913-L916

When checking the validity of recorded data based on the OWL restrictions, there is no easy way to indicate if these different restrictions are met.

Is there a reason to make a distinction between those two data types in the owl files? Why not declare every restriction on `float` a restriction on `double`?

**Comment by daniel86** [comment]
Well there is probably no strong reason and it happened juts by accident.
However, it is not really the decision of KnowRob what datatypes exist as we rather employ
the XSD vocabulary. So it would not be good to only support one of them.
