### ISSUE TITLE
New Features for the RoboHow Web Console

### ISSUE THREAD

**Issue by fairlight1337** [knowrob/knowrob#32]
Hey there,

@hatguy and me just discussed some open topics that could be tackled in the near future within the RoboHow Web Console interface:

 - [ ] Dynamic listing (and loading) of experiments (contrary to having fixed a list of experiments in the query library)
 - [ ] Create default statistics/information blocks from experiment data (for a quick analysis/glance on what the experiment consists of/includes/resulted in)
 - [ ] Having tabs in the main display (e.g. switching between the 3D canvas and the plan tree, as both are pretty big and are displaying kind of "main information")
 - [ ] Make "play" control slider work, introduce a play/stop button, allow mouse interaction with it
 - [ ] Create personal query libraries (personalized in terms of creating own queries, and maintaining them for future container runs - strongly related to @knowrob's Docker integration)
 - [ ] General bug fixes (left-over glitches from the first implementation)

For a general idea of how this could look like in conjunction with what's already there, see here:
![Web Console Sketch](http://daily-service.de/optinetics.net/data/sketch_webconsole.jpeg)

**Comment by knowrob** [comment]
I haven't used it yet, but would be interested to learn more about its capabilties.
