### ISSUE TITLE
Installation troubles on Ubuntu 20 (with ROS Noetic)

### ISSUE THREAD

**Issue by jpcoffelt** [knowrob/knowrob#321]
I am having troubles installing KnowRob on Ubuntu 20 with ROS Noetic. When I get to this step:

`rosdep install --ignore-src --from-paths .`

I receive this error:

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rosprolog: No definition of [python-future] for OS version [focal]
```

However, cloning directly via

`git clone https://github.com/knowrob/rosprolog.git`

and then making seemed to work.

**Comment by sasjonge** [comment]
I fixed this issue with this PR:

https://github.com/knowrob/rosprolog/pull/20

During the installation on Noetic, you will have to make sure that you have the noetic branch of rosprolog, before you build your workspace.
