### ISSUE TITLE
How to download the NEEMS

### ISSUE THREAD

**Issue by jophone** [knowrob/knowrob#331]
I read the NEEM-Handbook and followed it instruction to install Hadoop and DVC. However, when i try to download specific episodes using `dvc get` or `dvc pull`, it seems that my host can't connect to the hadoop cluster. 
how to solve this problem？ Is it only possible to download via the university’s intranet?

The error message as follow:
"INFO ipc.Client: Retrying connect to server: 134.102.137.65/134.102.137.65:9000. Already tried 15 time(s); maxRetries=45"
"Caused by: java.io.InterruptedIOException: Interrupted while waiting for IO on channel java.nio.channels.SocketChannel[connection-pending remote=134.102.137.65/134.102.137.65:9000]. Total timeout mills is 20000, 15242 millis timeout left."
"ERROR: unexpected error - [Errno 255] Opening HDFS file '/neems/ease-2020-pr2-setting-up-table/fe/c13d30d60434f8f1c0ffc4999ead57' failed. Detail: [errno 255] Unknown error 255  "

**Comment by sasjonge** [comment]
Hello, I think the better repository for this issue would have been the SOMA repo. I think I resolved the problem with you by sending the files, so I would close this issue here.
