### ISSUE TITLE
Installation error: catkin_make fails  (can't download SOMA-HOME-current)

### ISSUE THREAD

**Issue by Dorteel** [knowrob/knowrob#358]
Hi,

I'm trying to install KnowRob following the instructions, but getting a timeout when running catkin_make. 
```console
-- Downloading ontology SOMA-current.
-- Downloading ontology SOMA-HOME-current.
CMake Error at knowrob/cmake/ontologies.cmake:48 (message):
  Failed to download ontology
  https://ease-crc.github.io/soma/owl/current/SOMA-HOME.owl: "Timeout was
  reached"
Call Stack (most recent call first):
  knowrob/CMakeLists.txt:45 (install_ontology)


-- Configuring incomplete, errors occurred!
See also "/home/dorteel/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/dorteel/catkin_ws/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:320: cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
```
Do you have any suggestions? I'm not sure why this happens, as I can access [SOMA-HOME](https://ease-crc.github.io/soma/owl/current/SOMA-HOME.owl) through my browser.
Thanks in advance!

**Comment by nitin5** [comment]
I am able to install Knowrob today. 

Are you able to open link 'https://ease-crc.github.io/soma/owl/current/SOMA-HOME.owl' in browser? Just to check whether you have connectivity to the site.

**Comment by daniel86** [comment]
Probably was a temporary outage of some server.
