### ISSUE TITLE
visualization_msgs should be a dependency in package.xml

### ISSUE THREAD

**Issue by Sanic** [knowrob/knowrob#374]
The visualization_msgs package is used in this file:

https://github.com/knowrob/knowrob/blob/875af93907af35b94e1adedec5edf35625b6d7a5/include/knowrob/ros/marker/publisher.h#L9

**Comment by daniel86** [comment]
Thanks for the report, dependency is added with this commit: https://github.com/knowrob/knowrob/commit/4aa767b743d2fef2e66f4bd05dcd886418e4364f
