### ISSUE TITLE
Modal branch: AskOne does not terminate

### ISSUE THREAD

**Issue by sasjonge** [knowrob/knowrob#378]
If trying to run a ask-one query the program doesn't terminate and shows this warning:

> [warning] an exception occurred for graph query ((triple(X, swrl_test:hasNumber, Num) ∧ triple(swrl_test:'Fred', swrl_test:hasSibling, X))): mng_error(cursor_error,unrecognized field 'limit').

I wrote a test case to reproduce this problem on the askOneTest Branch:

https://github.com/knowrob/knowrob/blob/0843af51d1f036f48e1bcf25cd48f6042340d6a8/tests/KnowledgeBaseTest.cpp#L196

**Comment by daniel86** [comment]
fixed with #379
