### ISSUE TITLE
Update KnowRob for indigo

### ISSUE THREAD

**Issue by knowrob** [knowrob/knowrob#45]
- Add rosdep definitions for Ubuntu Trusty to rosdistro
- Test with new Prolog version in Ubuntu Trusty
- Update installation instructions

**Comment by Sanic** [comment]
Hey logicmoo,

i just tried out the recent json_prolog service on indigo, and it worked for me so far.
Updating rosjava seems to be the key, as i stated in the mentioned in the rosjava issue.
Can you please give us some feedback if also works for you?

Greetings

**Comment by knowrob** [comment]
Works for me as well when installing rosjava and KnowRob using the following Dockerfiles (which list all required commands to be performed, starting from a plain Ubuntu 14.04). 

https://github.com/knowrob/docker/blob/master/indigo-swi-rosjava/Dockerfile
https://github.com/knowrob/docker/blob/master/indigo-knowrob-interactive/Dockerfile
