### ISSUE TITLE
Knowrob installation stops at "rosdep install knowrob" phase.

### ISSUE THREAD

**Issue by andrzej-at-mazurkiewicz-org** [knowrob/knowrob#47]
Good Afternoon.

I tried to install knowrob on brand-new 32bit trusty kubuntu.
After installing of the ros-indigo-desktop-full, I have created a
separate user knowrob.
I have used the following procedure within the knowrob account.

export ROS_WORKSPACE=$HOME/catkin_ws/src 
mkdir -p $ROS_WORKSPACE
cd $ROS_WORKSPACE
~/catkin_ws/src$ catkin_init_workspace
~/catkin_ws/src$ cd ..
~/catkin_ws$ catkin_make
# Result OK
Base path: /home/knowrob/catkin_ws
Source space: /home/knowrob/catkin_ws/src
Build space: /home/knowrob/catkin_ws/build
Devel space: /home/knowrob/catkin_ws/devel
Install space: /home/knowrob/catkin_ws/install
####
...

echo "" > $ROS_WORKSPACE/.rosinstall
# Without the above step rosws merge has not worked

rosws merge
https://raw.github.com/knowrob/knowrob/indigo-devel/rosinstall/knowrob-all.rosinstall
# OK
rosws update

# Fetching files - OK

rosdep install knowrob
######################
I HAVE GOT THE ERROR
######################

ERROR: the following packages/stacks could not have their rosdep keys
resolved to system dependencies:
knowrob: Cannot locate rosdep definition for [tf_prolog]

################################################

I have noticed that last week manifest.xml have been replaced by
package.xml, so I cannot proceed with catkin_make.

===================================================

Below are my environment variables:
knowrob@andrzej-virtual-machine:~$ env | grep ROS
ROS_ROOT=/opt/ros/indigo/share/ros
ROS_PACKAGE_PATH=/home/knowrob/catkin_ws/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks
ROS_MASTER_URI=http://localhost:11311
ROS_WORKSPACE=/home/knowrob/catkin_ws/src
ROS_TEST_RESULTS_DIR=/home/knowrob/catkin_ws/build/test_results
ROSLISP_PACKAGE_DIRECTORIES=/home/knowrob/catkin_ws/devel/share/common-lisp
ROS_DISTRO=indigo
ROS_ETC_DIR=/opt/ros/indigo/etc/ros

I have no idea how to go on.

Regards
Andrzej Mazurkiewicz

**Comment by knowrob** [comment]
Nothing to be fixed, has been discussed in PM
