### ISSUE TITLE
Java classpath construction does not work properly with catkin 'install' space

### ISSUE THREAD

**Issue by mtenorth** [knowrob/knowrob#69]
The current procedure of constructing the Java classpath by finding and concatenating classpath.txt files in the dependent ROS packages does not scale to catkin install spaces. The classpath.txt contains global paths and references to the src and devel spaces that should not be in there.

Possibly there is a new way of discovering rosjava projects in dependent catkin packages in the Indigo release of rosjava?

**Comment by daniel86** [comment]
no java builds are supported anymore. Users with java code need to rely on rosjava for setting up their classpath
