### ISSUE TITLE
install instructions on website outdated?

### ISSUE THREAD

**Issue by airballking** [knowrob/knowrob#91]
The install instructions on ```knowrob.org``` point at the rosinstall-file of the indigo-branch. Those, in turn, point at the indigo-branch. However, that branch has not seen much activity, and the repository has the master-branch as default. Should the install instruction on the websites be changed to point at the master-branch?

@daniel86 @asilx could you please clarify?

**Comment by daniel86** [comment]
true, should be master instead. Don't have credentials with me. Will change the URL's later when I am home. Thanks for reporting!

**Comment by airballking** [comment]
ping
