### ISSUE TITLE
Logging sent queries by the robot and the answers to these 

### ISSUE THREAD

**Issue by asilx** [knowrob/knowrob#99]
During the execution time, the planner makes some queries using json_prolog. A logging mechanism for these queries should be implemented

**Comment by daniel86** [comment]
I already created a predicate and a query logging ontology for that purpose.
The predicate is called _cram_logged_query_, you can it find [here](https://github.com/knowrob/knowrob_addons/blob/master/knowrob_cram/prolog/knowrob_cram.pl#L129).
